export const categories = [
  {
    id: 'basic',
    title: 'Basic',
    description: 'Simple, elegant animations perfect for getting started with @wix/interact.',
    docsLink: '#',
    docsLabel: 'docs/viewEnter',
    compact: true,
    examples: [
      {
        id: 'hover',
        title: 'Hover',
        htmlPath: 'examples/basic/hover.html',
      },
      {
        id: 'click',
        title: 'Click',
        htmlPath: 'examples/basic/click.html',
      },
      {
        id: 'view-enter',
        title: 'View Enter',
        htmlPath: 'examples/basic/view-enter.html',
        autoScroll: true,
      },
      {
        id: 'pointer-move',
        title: 'Pointer Move',
        htmlPath: 'examples/basic/pointer-move.html',
      },
      {
        id: 'scroll',
        title: 'Scroll',
        htmlPath: 'examples/basic/scroll.html',
        autoScroll: true,
        viewportWidth: 665,
      },
    ],
  },
  {
    id: 'carousel',
    title: 'Gallery',
    description: 'Beautiful scrolling gallery layouts that enhance visual storytelling.',
    docsLink: '#',
    docsLabel: 'docs/viewProgress',
    layout: 'gallery-bento',
    examples: [
      {
        id: 'cards-3d-carousel',
        title: '3D Carousel',
        htmlPath: 'examples/carousel/cards-3d-carousel.html',
        autoScroll: true,
        viewportWidth: 1400,
        viewportHeight: 962,
      },
      {
        id: 'card-spread',
        title: 'Card Spread',
        htmlPath: 'examples/carousel/CardSpread.html',
        autoScroll: true,
        viewportWidth: 1400,
      },
      {
        id: 'mouse-track-gallery',
        title: 'Infinite Gallery',
        htmlPath: 'examples/carousel/mouse-track-gallery.html',
      },
      {
        id: 'sphere-interact',
        title: '3D Sphere',
        htmlPath: 'examples/carousel/sphere-interact.html',
        autoScroll: true,
        viewportWidth: 1400,
      },
    ],
  },
  {
    id: 'layout',
    title: 'Layout',
    description: 'Dynamic grid and list animations for complex content arrangements.',
    docsLink: '#',
    docsLabel: 'docs/lists',
    examples: [
      {
        id: 'column-shutters',
        title: 'Column Shutters',
        htmlPath: 'examples/layout/column-shutters.html',
        viewportWidth: 1000,
      },
      {
        id: 'parting-list',
        title: 'Parting List',
        htmlPath: 'examples/layout/parting-list.html',
        autoScroll: true,
        viewportWidth: 1600,
      },
    ],
  },
  {
    id: 'ui-elements',
    title: 'UI Items',
    description: 'Interactive micro-animations for buttons, forms, and interface components.',
    docsLink: '#',
    docsLabel: 'docs/pointerMove',
    gridCols: 3,
    gridGap: 24,
    examples: [
      {
        id: 'label',
        title: 'Labels',
        htmlPath: 'examples/ui-elements/label.html',
        colSpan: 2,
        rowSpan: 2,
        viewportWidth: 1000,
      },
      {
        id: 'lock-toggle',
        title: 'Lock Toggle',
        htmlPath: 'examples/ui-elements/lock-toggle.html',
        viewportWidth: 565,
      },
      {
        id: 'on-off-toggle',
        title: 'On/Off Toggle',
        htmlPath: 'examples/ui-elements/on-off-toggle.html',
        viewportWidth: 650,
      },
      {
        id: 'dropdown',
        title: 'Dropdown',
        htmlPath: 'examples/ui-elements/dropdown.html',
        viewportWidth: 670,
      },
      {
        id: 'password-input',
        title: 'Password Input',
        htmlPath: 'examples/ui-elements/password-input.html',
        viewportWidth: 615,
      },
      {
        id: 'radio-buttons',
        title: 'Radio Buttons',
        htmlPath: 'examples/ui-elements/radio-buttons.html',
        viewportWidth: 695,
      },
      {
        id: 'search-input',
        title: 'Search Input',
        htmlPath: 'examples/ui-elements/search-input.html',
        viewportWidth: 640,
      },
      {
        id: 'smiley-nav',
        title: 'Navigation',
        htmlPath: 'examples/ui-elements/smiley-nav.html',
      },
    ],
  },
  {
    id: 'custom-effects',
    title: 'Custom',
    description: 'Build your own effects with custom keyframes and pointer-driven interactions.',
    docsLink: '#',
    docsLabel: 'docs/customEffect',
    examples: [],
  },
];
